on:
  release:
    types: [created]

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      BINARY_NAME: xdp-ip-counter
      BUILD_DIR: ./target/x86_64-unknown-linux-musl/release/

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly

      - name: Install dependencies
        run: |
          cargo install bpf-linker
          rustup target add x86_64-unknown-linux-musl

      - name: Build binary
        run: |
          cargo xtask build-ebpf --release
          cargo build --release --target=x86_64-unknown-linux-musl

      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.3.2
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Compress binary
        uses: a7ul/tar-action@v1.1.0
        id: compress
        with:
          command: c
          cwd: ${{ env.BUILD_DIR }}
          files: |
            ./${{env.BINARY_NAME}}
          outPath: ${{env.BINARY_NAME}}-${{ steps.get_release.outputs.tag_name }}-linux-x86_64.tar.gz

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{env.BINARY_NAME}}-${{ steps.get_release.outputs.tag_name }}-linux-x86_64.tar.gz
